W8D1/reddit-clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'subs#index'
  resources :users
  resource :session, only: %i[create destroy new]
  resources :subs do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  resources :posts do
    resources :comments, only: :new
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  resources :comments, only: %i[create show] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
end

W8D1/reddit-clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
  belongs_to :sub

  belongs_to :author,
             foreign_key: :author_id,
             class_name: :User

  has_many :post_subs

  has_many :subs,
           through: :post_subs,
           source: :sub

  has_many :comments

  has_many :votes, as: :votable
  # def sub_ids=(sub_ids)
  #   debugger
  #   sub_ids.each do |_k, s_id|
  #     PostSub.create(sub_id: s_id, post_id: self.id)
  #   end
  # end

  def top_level_comments
    comments.where(parent_comment_id: nil)
  end

  # hash of comments: parent_id => [child_comments]
  def comments_by_parent_id
    h = Hash.new { |hash, k| hash[k] = [] }
    comments.includes(:author).each_with_object(h) do |comment, hash|
      hash[comment.parent_comment_id] << comment
    end
  end

  def vote_count
    votes.sum(:value)
  end

  def upvoted_by?(user)
    Vote.exists?(user_id: user.id, votable_id: id, votable_type: 'Post', value: 1)
  end

  def downvoted_by?(user)
    Vote.exists?(user_id: user.id, votable_id: id, votable_type: 'Post', value: -1)
  end
end

W8D1/reddit-clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, :session_token, uniqueness: true
  attr_reader :password
  after_initialize :ensure_session_token

  has_many :subs,
           foreign_key: :moderator_id,
           class_name: :Sub

  has_many :posts,
           foreign_key: :author_id,
           class_name: :Post,
           dependent: :destroy

  has_many :comments,
           foreign_key: :author_id

  has_many :votes

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user if user && user.is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.base64(64)
    save!
    session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.base64(64)
  end
end

W8D1/reddit-clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index; end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def post_params
    # debugger
    params[:post][:sub_ids]&.each do |_k, id|
      PostSub.create(sub_id: id, post_id: params[:id])
    end
    params.require(:post).permit(:title, :url, :content, :author_id, :sub_id, sub_ids: [])
  end

  def vote(dir)
    @post = Post.find(params[:id])
    vote = @post.votes.find_or_initialize_by(user: current_user)
    flash[:errors] = vote.errors.full_messages unless vote.update(value: dir)
    redirect_to sub_url(@post.sub_id)
  end

  def upvote
    vote(1)
  end

  def downvote
    vote(-1)
  end
end

W8D1/reddit-clone/app/helpers/posts_helper.rb
module PostsHelper
end

W8D1/reddit-clone/app/views/posts/_form.html.erb
<% action = post.persisted? ? post_url(post) : posts_url %>
<% method = post.persisted? ? :patch : :post %>
<% button_text = post.persisted? ? "Update" : "Create" %>

<form action="<%= action %>" method="POST">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="<%= method %>">

  <label>Title
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  <br>

  <label>Url
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label>

  <br>
  <br>
  <label>Content
    <textarea cols="40" rows="5" name="post[content]"><%= post.content %></textarea>
  </label>
  <br>

  <label>Subs: 
    <% subs = post.subs %>
    <% Sub.all.each.with_index do |sub, idx| %>
      <input type="checkbox" name="post[sub_ids][<%= idx %>]"
             value="<%= sub.id %>"
             <%= subs.include?(sub) ? 'checked' : '' %>><%= sub.title %>
    <% end %>
  </label>
  <br>
  <input type="submit" value="<%= button_text %>">
</form>

W8D1/reddit-clone/app/views/posts/edit.html.erb
<h2>Edit</h2>

<%= render 'form', post: @post %>

W8D1/reddit-clone/app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form', post: @post %>

<br>
<%= link_to 'Subs', subs_url %> | <%= link_to 'All Posts', posts_url %>

W8D1/reddit-clone/app/views/posts/show.html.erb
<h3><%= @post.title %></h3>

<h4>Content:</h4>

<%= @post.content %>

<h3>Subs</h3>
<ul>
  <% @post.subs.each do |sub| %>
    <li><%= link_to sub.title, sub_url(sub) %></li>
  <% end %>
</ul>

<h3>Comments</h3>

<%= link_to 'Comment on this post!', new_post_comment_url(@post) %>

<ul>
  <!-- Remove N+1 query on comments -->
  <% @all_comments = @post.comments.includes(:author).sort_by(&:vote_count).reverse %>
  <% @all_comments.each do |comment| %>
    <% if comment.parent_comment_id.nil? %>
      <!-- Only recurse on top-level comments -->
      <%= render 'comments/comment', comment: comment %>
    <% end %>
  <% end %>
</ul>

<%= link_to 'Edit', edit_post_url(@post) %>