W7D2/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'bands#index'
  resources :users
  resource :session, only: %i[new create destroy]

  resources :bands do
    resources :albums, only: :new
  end
  resources :albums, only: %i[create edit destroy show index update] do
    resources :tracks, only: :new
  end

  resources :tracks, only: %i[create edit show index update destroy]
  resources :notes, only: %i[create destroy]
end

W7D2/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  attr_reader :password

  validates :email, :password_digest, presence: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  after_initialize :ensure_session_token

  has_many :notes, dependent: :destroy

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user if user&.is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    save!
    session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

W7D2/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to bands_url #user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def destroy
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W7D2/music_app/app/views/users/index.html.erb
<h1>Users</h1>

<%= render 'shared/errors' %>
<ul>
  <% @users.each do |user|  %>
    <li><%= user.id %>: <%= user.email %></li>
  <% end %>
</ul>

<a href="<%= new_user_url %>">Create User</a>

W7D2/music_app/app/views/users/new.html.erb
<%= render 'shared/errors' %>

<h2>Sign Up</h2>

<%= render 'shared/login', action: :signup %>

W7D2/music_app/app/views/users/show.html.erb
<h2>User <%= @user.id %></h2>

<%= render 'shared/errors' %>

<table>
  <tr>
    <th>Id</th>
    <th>Email</th>
  </tr>
  <tbody>
    <tr>
      <td><%= @user.id %></td>
      <td><%= @user.email %></td>
    </tr>
  </tbody>
</table>

<a href="<%= users_url %>">Home</a>