W7D2/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'bands#index'
  resources :users
  resource :session, only: %i[new create destroy]

  resources :bands do
    resources :albums, only: :new
  end
  resources :albums, only: %i[create edit destroy show index update] do
    resources :tracks, only: :new
  end

  resources :tracks, only: %i[create edit show index update destroy]
  resources :notes, only: %i[create destroy]
end

W7D2/music_app/app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :bigint           not null, primary key
#  user_id    :integer          not null
#  track_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  note       :text
#
class Note < ApplicationRecord
  validates :user_id, :track_id, presence: true
  belongs_to :user
  belongs_to :track
end

W7D2/music_app/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_logged_in
  
  def create
    note = current_user.notes.new(note_params)
    note.save
    flash[:errors] = note.errors.full_messages
    redirect_to track_url(note.track_id)
  end

  def destroy
    note = current_user.notes.find(params[:id])
    note.destroy
    redirect_to track_url(note.track_id)
  end

  private

  def note_params
    params.require(:note).permit(:user_id, :track_id, :note)
  end
end

W7D2/music_app/app/helpers/notes_helper.rb
module NotesHelper
end

W7D2/music_app/app/views/notes/_form.html.erb
<form action="<%= notes_url %>" method="POST">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="POST">

  <input type="hidden" name="note[track_id]" value="<%= track.id %>"
  <label>Leave note:
    <textarea name="note[note]" value=""></textarea>
  </label>
  
  <input type="submit" value="Submit">
</form>

W7D2/music_app/app/views/notes/_note.html.erb
<!-- takes a 'note' local -->

<p>
  <strong><%= note.user.email %></strong> says
</p>

<ul>
  <p>
    <%= note.note %>
  </p>
</ul>

<% if logged_in? && note.user_id == current_user.id %>
  <form action="<%= note_url(note) %>" method="POST">
    <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete">
  </form>
<% end %>