W8D1/reddit-clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'subs#index'
  resources :users
  resource :session, only: %i[create destroy new]
  resources :subs do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  resources :posts do
    resources :comments, only: :new
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  resources :comments, only: %i[create show] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
end

W8D1/reddit-clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, :session_token, uniqueness: true
  attr_reader :password
  after_initialize :ensure_session_token

  has_many :subs,
           foreign_key: :moderator_id,
           class_name: :Sub

  has_many :posts,
           foreign_key: :author_id,
           class_name: :Post,
           dependent: :destroy

  has_many :comments,
           foreign_key: :author_id

  has_many :votes

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user if user && user.is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.base64(64)
    save!
    session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.base64(64)
  end
end

W8D1/reddit-clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: %i[destroy show]

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to users_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user&.destroy
    redirect_to users_url # @user && @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W8D1/reddit-clone/app/views/users/index.html.erb
<h1>All Users</h1>

<div>
    <ul>
        <% @users.each do |user| %>
            <li><a href="<%= user_url(user) %>"><%= user.username %></a></li>
        <% end %>
    </ul>
</div>

<%= link_to 'Subs', subs_url %>

W8D1/reddit-clone/app/views/users/new.html.erb
<h1>Sign Up</h1>

<div>
    <form action="<%= users_url %>" method="POST">
        <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
        <label>Username: 
            <input name="user[username]" value="">
        </label>
        <label>Password: 
            <input type="password" name="user[password]" value="">
        </label>
        <button type='submit'>Sign Up</button>
    </form>
</div>